version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token eyJhIjoiODBjNjYxMzhiYTViMzkwNzJjODMyZmU3NzNiZmMxNTYiLCJ0IjoiNjg1OTNmNWQtY2YyMi00MjE2LTg4OWItNzZiM2UxYzg5MzJjIiwicyI6Ik1tTXdZV1k0TTJVdE1qZzJaQzAwTWpGaUxXSmxaVFl0TUdJell6Vm1OekE1T0RCbCJ9
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.2

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.3

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.4

  nextcloud:
    image: nextcloud:stable-apache
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - postgres
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.5

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: <change-me>
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.6

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    networks:
      dotnetwork:
        ipv4_address: 10.0.0.7

volumes:
  portainer:
    name: portainer
  postgres:
    name: postgres
  nextcloud:
    name: nextcloud

networks:
  dotnetwork:
    name: dotnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1